platform :osx, '10.10'

pod 'AFNetworking', '~> 2.6'
pod 'CocoaLumberjack'
pod "XCDLumberjackNSLogger"
pod 'AFNetworkActivityLogger'
pod "HockeySDK-Mac"
target 'waka_watcherTests' do
pod 'OHHTTPStubs'
end
target 'waka_watcherUITests' do
pod 'OHHTTPStubs'
end